### PR TITLE
Move workflow inline scripts to separate files.

### PR DESCRIPTION
**Pull request by parasense**
Related: HACBS-430

Signed-off-by: Jon Disnard <jdisnard@redhat.com>

### CODE REVIEW

**Review by davidmogar — COMMENTED** [review]
Much cleaner. Check your PR #2 before going ahead with this one.

**Comment by parasense** [comment]
Any reason this should not be merged today?

**Comment by davidmogar** [comment]
Could you rename files to `whatever.sh`? After that, feel free to merge.

**Comment by parasense** [comment]
> Could you rename files to `whatever.sh`? After that, feel free to merge.

:+1:

**Pull request merged**
